---
version: 2
multicolumn: true
web-width: 800
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/cannabisactive/cannabisactive.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/112120/articles/320895/master/file/figures/cannabisactive/cannabisactive.png"
    folder_url: "/users/112120/articles/320895/master/folder/figures/cannabisactive"
